const data = [
  {
    name: 'Electric Guitar',
    type: 'string',
    popularity: 1,
    price: 305,
    isInStock: true,
  },
  {
    name: 'Drum Kit',
    type: 'percussion',
    popularity: 3,
    price: 700,
    isInStock: false,
  },
  {
    name: 'Bass Guitar',
    type: 'string',
    popularity: 2,
    price: 130,
    isInStock: true,
  },
  {
    name: 'Cello',
    type: 'string',
    popularity: 6,
    price: 245,
    isInStock: true,
  },
  {
    name: 'Trumpet',
    type: 'brass',
    popularity: 11,
    price: 130,
    isInStock: true,
  },
  {
    name: 'Trombone',
    type: 'brass',
    popularity: 9,
    price: 650,
    isInStock: false,
  },
  {
    name: 'Shaker',
    type: 'percussion',
    popularity: 64,
    price: 12,
    isInStock: true,
  },
  {
    name: 'Guitar picks',
    type: 'accessories',
    popularity: 27,
    price: 6,
    isInStock: true,
  },
  {
    name: 'Tuner',
    type: 'accessories',
    popularity: 94,
    price: 22,
    isInStock: false,
  },
];
